/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/check-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_checkStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_findAll"];
        put?: never;
        post: operations["AuthController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AuthController_deactivate"];
        options?: never;
        head?: never;
        patch: operations["AuthController_update"];
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SettingsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["SettingsController_update"];
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesController_findAll"];
        put?: never;
        post: operations["CategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesController_findById"];
        put?: never;
        post?: never;
        delete: operations["CategoriesController_deactivate"];
        options?: never;
        head?: never;
        patch: operations["CategoriesController_update"];
        trace?: never;
    };
    "/api/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CandlesController_findAll"];
        put?: never;
        post: operations["CandlesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CandlesController_findById"];
        put?: never;
        post?: never;
        delete: operations["CandlesController_deactivate"];
        options?: never;
        head?: never;
        patch: operations["CandlesController_update"];
        trace?: never;
    };
    "/api/packaging-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PackagingTypesController_findAll"];
        put?: never;
        post: operations["PackagingTypesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packaging-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PackagingTypesController_findById"];
        put?: never;
        post?: never;
        delete: operations["PackagingTypesController_deactivate"];
        options?: never;
        head?: never;
        patch: operations["PackagingTypesController_update"];
        trace?: never;
    };
    "/api/card-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CardTypesController_findAll"];
        put?: never;
        post: operations["CardTypesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/card-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CardTypesController_findById"];
        put?: never;
        post?: never;
        delete: operations["CardTypesController_deactivate"];
        options?: never;
        head?: never;
        patch: operations["CardTypesController_update"];
        trace?: never;
    };
    "/api/products/preview-cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProductsController_previewCost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findAll"];
        put?: never;
        post: operations["ProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findById"];
        put?: never;
        post?: never;
        delete: operations["ProductsController_deactivate"];
        options?: never;
        head?: never;
        patch: operations["ProductsController_update"];
        trace?: never;
    };
    "/api/products/{id}/reapply-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProductsController_reapplyTemplates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/price-override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ProductsController_setPriceOverride"];
        trace?: never;
    };
    "/api/products/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProductsController_addImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ProductsController_removeImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overhead-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OverheadController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overhead-periods/current-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OverheadController_currentRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overhead-periods/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OverheadController_close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuppliesController_findAll"];
        put?: never;
        post: operations["SuppliesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplies/low-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuppliesController_findLowStock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplies/cost-drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuppliesController_findWithCostDrift"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supplies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuppliesController_findById"];
        put?: never;
        post?: never;
        delete: operations["SuppliesController_deactivate"];
        options?: never;
        head?: never;
        patch: operations["SuppliesController_update"];
        trace?: never;
    };
    "/api/supplies/{id}/apply-suggested-cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SuppliesController_applySuggestedCost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PurchasesController_findAll"];
        put?: never;
        post: operations["PurchasesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PurchasesController_findById"];
        put?: never;
        post?: never;
        delete: operations["PurchasesController_deactivate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AssetsController_findAll"];
        put?: never;
        post: operations["AssetsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AssetsController_findById"];
        put?: never;
        post?: never;
        delete: operations["AssetsController_deactivate"];
        options?: never;
        head?: never;
        patch: operations["AssetsController_update"];
        trace?: never;
    };
    "/api/expenses/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExpensesController_findAllCategories"];
        put?: never;
        post: operations["ExpensesController_createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExpensesController_findAll"];
        put?: never;
        post: operations["ExpensesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ExpensesController_deactivate"];
        options?: never;
        head?: never;
        patch: operations["ExpensesController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignInDto: {
            /** @example admin */
            username: string;
            /** @example Admin123! */
            password: string;
        };
        SignInResponseDto: {
            accessToken: string;
            user: {
                id: number;
                username: string;
                fullName: string;
                role: string;
            };
        };
        CreateUserDto: {
            /** @example ana */
            username: string;
            /** @example Ana Perez */
            fullName: string;
            password: string;
            /**
             * @default employee
             * @enum {string}
             */
            role: "employee" | "admin" | "super_user";
        };
        UpdateUserDto: {
            /** @example ana */
            username?: string;
            /** @example Ana Perez */
            fullName?: string;
            password?: string;
            /**
             * @default employee
             * @enum {string}
             */
            role: "employee" | "admin" | "super_user";
        };
        UpdateSettingsDto: {
            legalName?: string;
            brandName?: string;
            logoUrl?: string;
            phone?: string;
            whatsapp?: string;
            /** Format: email */
            email?: string;
            city?: string;
            state?: string;
            businessHours?: string;
            instagramUrl?: string;
            facebookUrl?: string;
            tiktokUrl?: string;
            timezone?: string;
            currency?: string;
            minLeadTimeDays?: number;
            depositPct?: number;
            quotationValidityDays?: number;
            dailyWage?: number;
            workHoursPerDay?: number;
            meltBatchGrams?: number;
            defaultWastePct?: number;
            waxSupplyId?: number;
            fragranceSupplyId?: number;
            fragranceLoadPct?: number;
            fragranceSurcharge?: number;
            /** @enum {string} */
            overheadRateMode?: "DERIVED" | "FIXED";
            overheadRatePerMinute?: number;
            overheadMinSampleMinutes?: number;
            overheadMaxDeviationPct?: number;
            retailMarkupPct?: number;
            wholesaleMarkupPct?: number;
            wholesaleThresholdQty?: number;
            minMarginPct?: number;
            roundingMultiple?: number;
            supplyCostWindowDays?: number;
            supplyCostMaxSamples?: number;
            supplyCostAlertPct?: number;
            defaultAssetUsefulLifeMonths?: number;
            quotationTerms?: string;
            quotationFooterNote?: string;
            orderPolicyText?: string;
            quotationFolioPrefix?: string;
            orderFolioPrefix?: string;
            purchaseFolioPrefix?: string;
            paymentFolioPrefix?: string;
        };
        CreateCategoryDto: {
            /** @example Animalitos */
            name: string;
            /**
             * @description Color para diferenciar la categoria
             * @example #8A9A5B
             */
            colorHex: string;
            description?: string;
            coverImageUrl?: string;
            /** @default 0 */
            sortOrder: number;
            /** @default true */
            isVisibleOnLanding: boolean;
        };
        UpdateCategoryDto: {
            /** @example Animalitos */
            name?: string;
            /**
             * @description Color para diferenciar la categoria
             * @example #8A9A5B
             */
            colorHex?: string;
            description?: string;
            coverImageUrl?: string;
            /** @default 0 */
            sortOrder: number;
            /** @default true */
            isVisibleOnLanding: boolean;
        };
        CandleSupplyTemplateItemDto: {
            supplyId: number;
            quantity: number;
            /** @enum {string} */
            unit: "GRAM" | "KILOGRAM" | "MILLILITER" | "LITER" | "CENTIMETER" | "METER" | "PIECE" | "SHEET";
            note?: string;
        };
        CreateCandleDto: {
            /** @example Osito Chico */
            name: string;
            categoryId: number;
            /**
             * @description Gramos de cera de UNA pieza, sin merma
             * @example 15
             */
            grams: number;
            widthCm?: number;
            heightCm?: number;
            /**
             * @description Merma de vaciado, 0.03 = 3%
             * @default 0.03
             */
            wastePct: number;
            /**
             * @description Minutos de derretir y desmoldar de UN LOTE
             * @default 15
             */
            meltMinutes: number;
            /** @description Capacidad de la olla en gramos para este molde. Vacio = usa el default de Settings */
            meltBatchGrams?: number;
            waxSupplyId?: number;
            moldAssetId?: number;
            imageUrl?: string;
            /** @description Insumos propios de la vela (mecha, colorante): se repiten en todas sus variantes de empaque */
            supplyTemplate?: components["schemas"]["CandleSupplyTemplateItemDto"][];
        };
        UpdateCandleDto: {
            /** @example Osito Chico */
            name?: string;
            categoryId?: number;
            /**
             * @description Gramos de cera de UNA pieza, sin merma
             * @example 15
             */
            grams?: number;
            widthCm?: number;
            heightCm?: number;
            /**
             * @description Merma de vaciado, 0.03 = 3%
             * @default 0.03
             */
            wastePct: number;
            /**
             * @description Minutos de derretir y desmoldar de UN LOTE
             * @default 15
             */
            meltMinutes: number;
            /** @description Capacidad de la olla en gramos para este molde. Vacio = usa el default de Settings */
            meltBatchGrams?: number;
            waxSupplyId?: number;
            moldAssetId?: number;
            imageUrl?: string;
            /** @description Insumos propios de la vela (mecha, colorante): se repiten en todas sus variantes de empaque */
            supplyTemplate?: components["schemas"]["CandleSupplyTemplateItemDto"][];
        };
        PackagingSupplyTemplateItemDto: {
            supplyId: number;
            quantity: number;
            /** @enum {string} */
            unit: "GRAM" | "KILOGRAM" | "MILLILITER" | "LITER" | "CENTIMETER" | "METER" | "PIECE" | "SHEET";
            note?: string;
        };
        CreatePackagingTypeDto: {
            /** @example Celofan con Liston */
            name: string;
            description?: string;
            /**
             * @description Minutos de empaquetar UNA pieza
             * @default 0
             */
            packMinutes: number;
            /**
             * @description Minutos de diseno/armado POR PEDIDO que aporta este empaque
             * @default 0
             */
            setupMinutes: number;
            supplyTemplate?: components["schemas"]["PackagingSupplyTemplateItemDto"][];
        };
        UpdatePackagingTypeDto: {
            /** @example Celofan con Liston */
            name?: string;
            description?: string;
            /**
             * @description Minutos de empaquetar UNA pieza
             * @default 0
             */
            packMinutes: number;
            /**
             * @description Minutos de diseno/armado POR PEDIDO que aporta este empaque
             * @default 0
             */
            setupMinutes: number;
            supplyTemplate?: components["schemas"]["PackagingSupplyTemplateItemDto"][];
        };
        CardSupplyTemplateItemDto: {
            supplyId: number;
            quantity: number;
            /** @enum {string} */
            unit: "GRAM" | "KILOGRAM" | "MILLILITER" | "LITER" | "CENTIMETER" | "METER" | "PIECE" | "SHEET";
            note?: string;
        };
        CreateCardTypeDto: {
            /** @example Etiqueta 5x5 una cara */
            name: string;
            description?: string;
            widthCm?: number;
            heightCm?: number;
            /** @default 1 */
            printedSides: number;
            /**
             * @description Minutos de disenar el arte, POR PEDIDO
             * @default 15
             */
            setupMinutes: number;
            supplyTemplate?: components["schemas"]["CardSupplyTemplateItemDto"][];
        };
        UpdateCardTypeDto: {
            /** @example Etiqueta 5x5 una cara */
            name?: string;
            description?: string;
            widthCm?: number;
            heightCm?: number;
            /** @default 1 */
            printedSides: number;
            /**
             * @description Minutos de disenar el arte, POR PEDIDO
             * @default 15
             */
            setupMinutes: number;
            supplyTemplate?: components["schemas"]["CardSupplyTemplateItemDto"][];
        };
        ProductComponentItemDto: {
            candleId: number;
            /** @default 1 */
            quantity: number;
        };
        ProductSupplyItemDto: {
            supplyId: number;
            quantity: number;
            /** @enum {string} */
            unit: "GRAM" | "KILOGRAM" | "MILLILITER" | "LITER" | "CENTIMETER" | "METER" | "PIECE" | "SHEET";
            note?: string;
        };
        PreviewProductCostDto: {
            /**
             * @default SIMPLE
             * @enum {string}
             */
            kind: "SIMPLE" | "BOUQUET";
            candleId?: number;
            packagingTypeId?: number;
            cardTypeId?: number;
            /** @default 0 */
            extraSetupMinutes: number;
            /** @default 0 */
            extraPackMinutes: number;
            /** @default 0 */
            assemblyMinutes: number;
            components?: components["schemas"]["ProductComponentItemDto"][];
            additionalSupplies?: components["schemas"]["ProductSupplyItemDto"][];
        };
        CreateProductDto: {
            /** @example Osito Chico con Listón */
            name: string;
            categoryId: number;
            /**
             * @default SIMPLE
             * @enum {string}
             */
            kind: "SIMPLE" | "BOUQUET";
            /** @description Requerido si kind=SIMPLE */
            candleId?: number;
            /** @description Empaque del producto (Sola, Listón, Cajita, Tul...) */
            packagingTypeId?: number;
            cardTypeId?: number;
            description?: string;
            /** @default 0 */
            extraSetupMinutes: number;
            /** @default 0 */
            extraPackMinutes: number;
            /**
             * @description Solo para kind=BOUQUET: minutos de envolver y atar el ramo
             * @default 0
             */
            assemblyMinutes: number;
            /** @default true */
            allowsFragrance: boolean;
            /** @default true */
            isVisibleOnLanding: boolean;
            /**
             * @description Aparece primero en el catalogo y en "Destacados" del dashboard
             * @default false
             */
            isFeatured: boolean;
            /** @description Requerido si kind=BOUQUET: las velas que arma el ramo */
            components?: components["schemas"]["ProductComponentItemDto"][];
            /** @description Insumos ADICIONALES a los que ya aportan las plantillas de la vela, el empaque y la tarjeta (p. ej. un cascabel extra) */
            additionalSupplies?: components["schemas"]["ProductSupplyItemDto"][];
        };
        UpdateProductDto: {
            /** @example Osito Chico con Listón */
            name?: string;
            categoryId?: number;
            /**
             * @default SIMPLE
             * @enum {string}
             */
            kind: "SIMPLE" | "BOUQUET";
            /** @description Requerido si kind=SIMPLE */
            candleId?: number;
            /** @description Empaque del producto (Sola, Listón, Cajita, Tul...) */
            packagingTypeId?: number;
            cardTypeId?: number;
            description?: string;
            /** @default 0 */
            extraSetupMinutes: number;
            /** @default 0 */
            extraPackMinutes: number;
            /**
             * @description Solo para kind=BOUQUET: minutos de envolver y atar el ramo
             * @default 0
             */
            assemblyMinutes: number;
            /** @default true */
            allowsFragrance: boolean;
            /** @default true */
            isVisibleOnLanding: boolean;
            /**
             * @description Aparece primero en el catalogo y en "Destacados" del dashboard
             * @default false
             */
            isFeatured: boolean;
            /** @description Requerido si kind=BOUQUET: las velas que arma el ramo */
            components?: components["schemas"]["ProductComponentItemDto"][];
            /** @description Insumos ADICIONALES a los que ya aportan las plantillas de la vela, el empaque y la tarjeta (p. ej. un cascabel extra) */
            additionalSupplies?: components["schemas"]["ProductSupplyItemDto"][];
        };
        SetPriceOverrideDto: {
            /** @description null para volver a usar el precio calculado */
            retailPriceOverride?: number | null;
            wholesalePriceOverride?: number | null;
        };
        ClosePeriodDto: {
            year: number;
            month: number;
        };
        CreateSupplyDto: {
            /** @example Celofan transparente */
            name: string;
            sku?: string;
            /** @enum {string} */
            type: "WAX" | "FRAGRANCE" | "WICK" | "DYE" | "ALUMINUM_BASE" | "CELLOPHANE" | "RIBBON" | "LABEL" | "PRINTING" | "SEAL" | "BELL" | "SILICONE" | "BOX" | "TULLE" | "ACETATE" | "PAPER" | "OTHER";
            /** @enum {string} */
            unit: "GRAM" | "KILOGRAM" | "MILLILITER" | "LITER" | "CENTIMETER" | "METER" | "PIECE" | "SHEET";
            /** @description Costo por unidad base ($/g, $/pieza, etc.) */
            currentUnitCost: number;
            minStockQty?: number;
            /** @example bulto de 20 kg */
            defaultPackLabel?: string;
            /** @description Cuantas unidades base trae ese "bulto" */
            defaultBaseQtyPerPack?: number;
            /** @description Ayuda de captura: de una unidad base salen N piezas usables */
            yieldPerBaseUnit?: number;
            notes?: string;
        };
        UpdateSupplyDto: {
            /** @example Celofan transparente */
            name?: string;
            sku?: string;
            /** @enum {string} */
            type?: "WAX" | "FRAGRANCE" | "WICK" | "DYE" | "ALUMINUM_BASE" | "CELLOPHANE" | "RIBBON" | "LABEL" | "PRINTING" | "SEAL" | "BELL" | "SILICONE" | "BOX" | "TULLE" | "ACETATE" | "PAPER" | "OTHER";
            /** @enum {string} */
            unit?: "GRAM" | "KILOGRAM" | "MILLILITER" | "LITER" | "CENTIMETER" | "METER" | "PIECE" | "SHEET";
            /** @description Costo por unidad base ($/g, $/pieza, etc.) */
            currentUnitCost?: number;
            minStockQty?: number;
            /** @example bulto de 20 kg */
            defaultPackLabel?: string;
            /** @description Cuantas unidades base trae ese "bulto" */
            defaultBaseQtyPerPack?: number;
            /** @description Ayuda de captura: de una unidad base salen N piezas usables */
            yieldPerBaseUnit?: number;
            notes?: string;
        };
        CreatePurchaseItemDto: {
            /** @enum {string} */
            kind: "SUPPLY" | "ASSET" | "EXPENSE";
            /** @example 20 kilos de cera */
            description: string;
            /** @description Requerido si kind=SUPPLY */
            supplyId?: number;
            /** @description Si kind=ASSET y ya existe el activo (se le suma esta compra) */
            assetId?: number;
            /** @description Si kind=ASSET y es un activo nuevo: su nombre */
            assetName?: string;
            /**
             * @description Si kind=ASSET y es un activo nuevo
             * @enum {string}
             */
            assetKind?: "MOLD" | "TOOL" | "EQUIPMENT";
            /** @description Requerido si kind=EXPENSE */
            expenseCategoryId?: number;
            /**
             * @description Cuantos "bultos"/paquetes se compraron
             * @example 2
             */
            packsQty: number;
            /**
             * @description Unidades base que trae CADA paquete
             * @example 20000
             */
            baseQtyPerPack: number;
            /**
             * @description Precio de CADA paquete
             * @example 1978
             */
            pricePerPack: number;
        };
        CreatePurchaseDto: {
            purchasedAt: string;
            /** @example Mercado Libre */
            platform?: string;
            supplierName?: string;
            reference?: string;
            /** @default 0 */
            shippingCost: number;
            notes?: string;
            items: components["schemas"]["CreatePurchaseItemDto"][];
        };
        CreateAssetDto: {
            /** @example Molde vela rosa */
            name: string;
            /**
             * @default MOLD
             * @enum {string}
             */
            kind: "MOLD" | "TOOL" | "EQUIPMENT";
            acquiredAt: string;
            /** @default 1 */
            quantity: number;
            unitCost: number;
            usefulLifeMonths?: number;
            notes?: string;
        };
        UpdateAssetDto: {
            /** @example Molde vela rosa */
            name?: string;
            /**
             * @default MOLD
             * @enum {string}
             */
            kind: "MOLD" | "TOOL" | "EQUIPMENT";
            acquiredAt?: string;
            /** @default 1 */
            quantity: number;
            unitCost?: number;
            usefulLifeMonths?: number;
            notes?: string;
        };
        CreateExpenseCategoryDto: {
            /** @example Gas */
            name: string;
            /**
             * @default OVERHEAD
             * @enum {string}
             */
            kind: "OVERHEAD" | "NON_OPERATING";
        };
        CreateExpenseDto: {
            categoryId: number;
            /** @example Recarga de gas del taller */
            description: string;
            amount: number;
            /** @description Fecha en la que realmente se hizo el gasto */
            incurredAt: string;
            /** @description Mes al que se imputa (YYYY-MM-01). Default: el mes de incurredAt */
            periodMonth?: string;
        };
        UpdateExpenseDto: {
            categoryId?: number;
            /** @example Recarga de gas del taller */
            description?: string;
            amount?: number;
            /** @description Fecha en la que realmente se hizo el gasto */
            incurredAt?: string;
            /** @description Mes al que se imputa (YYYY-MM-01). Default: el mes de incurredAt */
            periodMonth?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponseDto"];
                };
            };
        };
    };
    AuthController_checkStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                /** @description Si es false, incluye tambien los registros dados de baja */
                onlyActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    SettingsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SettingsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                /** @description Si es false, incluye tambien los registros dados de baja */
                onlyActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CandlesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                /** @description Si es false, incluye tambien los registros dados de baja */
                onlyActive?: boolean;
                categoryId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CandlesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCandleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CandlesController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    CandlesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CandlesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCandleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    PackagingTypesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                /** @description Si es false, incluye tambien los registros dados de baja */
                onlyActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PackagingTypesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePackagingTypeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    PackagingTypesController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    PackagingTypesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PackagingTypesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePackagingTypeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    CardTypesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                /** @description Si es false, incluye tambien los registros dados de baja */
                onlyActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CardTypesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardTypeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    CardTypesController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    CardTypesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CardTypesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCardTypeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductsController_previewCost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewProductCostDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                /** @description Si es false, incluye tambien los registros dados de baja */
                onlyActive?: boolean;
                categoryId?: number;
                kind?: "SIMPLE" | "BOUQUET";
                /** @description Filtra los productos que el importador marco para revisar */
                needsReview?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductsController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductsController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductsController_reapplyTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductsController_setPriceOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPriceOverrideDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductsController_addImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_removeImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imageId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OverheadController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    OverheadController_currentRate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    OverheadController_close: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClosePeriodDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuppliesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                /** @description Si es false, incluye tambien los registros dados de baja */
                onlyActive?: boolean;
                type?: "WAX" | "FRAGRANCE" | "WICK" | "DYE" | "ALUMINUM_BASE" | "CELLOPHANE" | "RIBBON" | "LABEL" | "PRINTING" | "SEAL" | "BELL" | "SILICONE" | "BOX" | "TULLE" | "ACETATE" | "PAPER" | "OTHER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuppliesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSupplyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuppliesController_findLowStock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    SuppliesController_findWithCostDrift: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuppliesController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuppliesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuppliesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSupplyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuppliesController_applySuggestedCost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchasesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                /** @description Si es false, incluye tambien los registros dados de baja */
                onlyActive?: boolean;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PurchasesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePurchaseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    PurchasesController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    PurchasesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AssetsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                /** @description Si es false, incluye tambien los registros dados de baja */
                onlyActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetsController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetsController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExpensesController_findAllCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ExpensesController_createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExpenseCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExpensesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                /** @description Si es false, incluye tambien los registros dados de baja */
                onlyActive?: boolean;
                categoryId?: number;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExpensesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExpenseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExpensesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExpensesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExpenseDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
